import type { editor } from 'monaco-editor/esm/vs/editor/editor.api';

export const theme = {
  inherit: true,
  base: 'vs-dark' as editor.BuiltinTheme,
  colors: {
    'activityBar.activeBorder': '#f9826c',
    'activityBar.background': '#24292e',
    'activityBar.border': '#1b1f23',
    'activityBar.foreground': '#e1e4e8',
    'activityBar.inactiveForeground': '#6a737d',
    'activityBarBadge.background': '#0366d6',
    'activityBarBadge.foreground': '#ffffff',
    'badge.background': '#044289',
    'badge.foreground': '#c8e1ff',
    'breadcrumb.activeSelectionForeground': '#d1d5da',
    'breadcrumb.focusForeground': '#e1e4e8',
    'breadcrumb.foreground': '#959da5',
    'breadcrumbPicker.background': '#2b3036',
    'button.background': '#176f2c',
    'button.foreground': '#dcffe4',
    'button.hoverBackground': '#22863a',
    'button.secondaryBackground': '#444d56',
    'button.secondaryForeground': '#ffffff',
    'button.secondaryHoverBackground': '#586069',
    'checkbox.background': '#444d56',
    'checkbox.border': '#1b1f23',
    'debugToolBar.background': '#2b3036',
    descriptionForeground: '#959da5',
    'diffEditor.insertedTextBackground': '#28a74530',
    'diffEditor.removedTextBackground': '#d73a4930',
    'dropdown.background': '#2f363d',
    'dropdown.border': '#1b1f23',
    'dropdown.foreground': '#e1e4e8',
    'dropdown.listBackground': '#24292e',
    'editor.background': '#24292e',
    'editor.findMatchBackground': '#ffd33d44',
    'editor.findMatchHighlightBackground': '#ffd33d22',
    'editor.focusedStackFrameHighlightBackground': '#2b6a3033',
    'editor.foldBackground': '#58606915',
    'editor.foreground': '#e1e4e8',
    'editor.inactiveSelectionBackground': '#3392ff22',
    'editor.lineHighlightBackground': '#2b3036',
    'editor.linkedEditingBackground': '#3392ff22',
    'editor.selectionBackground': '#3392ff44',
    'editor.selectionHighlightBackground': '#17e5e633',
    'editor.selectionHighlightBorder': '#17e5e600',
    'editor.stackFrameHighlightBackground': '#c6902625',
    'editor.wordHighlightBackground': '#17e5e600',
    'editor.wordHighlightBorder': '#17e5e699',
    'editor.wordHighlightStrongBackground': '#17e5e600',
    'editor.wordHighlightStrongBorder': '#17e5e666',
    'editorBracketHighlight.foreground1': '#87cefa',
    'editorBracketHighlight.foreground2': '#da70d6',
    'editorBracketHighlight.foreground3': '#87cefa',
    'editorBracketHighlight.foreground4': '#da70d6',
    'editorBracketHighlight.foreground5': '#87cefa',
    'editorBracketHighlight.foreground6': '#da70d6',
    'editorBracketMatch.background': '#17e5e650',
    'editorBracketMatch.border': '#17e5e600',
    'editorCursor.foreground': '#c8e1ff',
    'editorGroup.border': '#1b1f23',
    'editorGroupHeader.tabsBackground': '#1f2428',
    'editorGroupHeader.tabsBorder': '#1b1f23',
    'editorGutter.addedBackground': '#28a745',
    'editorGutter.deletedBackground': '#ea4a5a',
    'editorGutter.modifiedBackground': '#2188ff',
    'editorIndentGuide.activeBackground': '#444d56',
    'editorIndentGuide.background': '#2f363d',
    'editorLineNumber.activeForeground': '#e1e4e8',
    'editorLineNumber.foreground': '#444d56',
    'editorOverviewRuler.border': '#1b1f23',
    'editorWhitespace.foreground': '#444d56',
    'editorWidget.background': '#1f2428',
    errorForeground: '#f97583',
    focusBorder: '#005cc5',
    foreground: '#d1d5da',
    'gitDecoration.addedResourceForeground': '#34d058',
    'gitDecoration.conflictingResourceForeground': '#ffab70',
    'gitDecoration.deletedResourceForeground': '#ea4a5a',
    'gitDecoration.ignoredResourceForeground': '#6a737d',
    'gitDecoration.modifiedResourceForeground': '#79b8ff',
    'gitDecoration.submoduleResourceForeground': '#6a737d',
    'gitDecoration.untrackedResourceForeground': '#34d058',
    'input.background': '#2f363d',
    'input.border': '#1b1f23',
    'input.foreground': '#e1e4e8',
    'input.placeholderForeground': '#959da5',
    'list.activeSelectionBackground': '#39414a',
    'list.activeSelectionForeground': '#e1e4e8',
    'list.focusBackground': '#044289',
    'list.hoverBackground': '#282e34',
    'list.hoverForeground': '#e1e4e8',
    'list.inactiveFocusBackground': '#1d2d3e',
    'list.inactiveSelectionBackground': '#282e34',
    'list.inactiveSelectionForeground': '#e1e4e8',
    'notificationCenterHeader.background': '#24292e',
    'notificationCenterHeader.foreground': '#959da5',
    'notifications.background': '#2f363d',
    'notifications.border': '#1b1f23',
    'notifications.foreground': '#e1e4e8',
    'notificationsErrorIcon.foreground': '#ea4a5a',
    'notificationsInfoIcon.foreground': '#79b8ff',
    'notificationsWarningIcon.foreground': '#ffab70',
    'panel.background': '#1f2428',
    'panel.border': '#1b1f23',
    'panelInput.border': '#2f363d',
    'panelTitle.activeBorder': '#f9826c',
    'panelTitle.activeForeground': '#e1e4e8',
    'panelTitle.inactiveForeground': '#959da5',
    'peekViewEditor.background': '#1f242888',
    'peekViewEditor.matchHighlightBackground': '#ffd33d33',
    'peekViewResult.background': '#1f2428',
    'peekViewResult.matchHighlightBackground': '#ffd33d33',
    'pickerGroup.border': '#444d56',
    'pickerGroup.foreground': '#e1e4e8',
    'progressBar.background': '#0366d6',
    'quickInput.background': '#24292e',
    'quickInput.foreground': '#e1e4e8',
    'scrollbar.shadow': '#00000088',
    'scrollbarSlider.activeBackground': '#6a737d88',
    'scrollbarSlider.background': '#6a737d33',
    'scrollbarSlider.hoverBackground': '#6a737d44',
    'settings.headerForeground': '#e1e4e8',
    'settings.modifiedItemIndicator': '#0366d6',
    'sideBar.background': '#1f2428',
    'sideBar.border': '#1b1f23',
    'sideBar.foreground': '#d1d5da',
    'sideBarSectionHeader.background': '#1f2428',
    'sideBarSectionHeader.border': '#1b1f23',
    'sideBarSectionHeader.foreground': '#e1e4e8',
    'sideBarTitle.foreground': '#e1e4e8',
    'statusBar.background': '#24292e',
    'statusBar.border': '#1b1f23',
    'statusBar.debuggingBackground': '#931c06',
    'statusBar.debuggingForeground': '#ffffff',
    'statusBar.foreground': '#d1d5da',
    'statusBar.noFolderBackground': '#24292e',
    'statusBarItem.prominentBackground': '#282e34',
    'tab.activeBackground': '#24292e',
    'tab.activeBorder': '#6c4df5',
    'tab.activeBorderTop': '#f9826c',
    'tab.activeForeground': '#e1e4e8',
    'tab.border': '#1b1f23',
    'tab.hoverBackground': '#24292e',
    'tab.inactiveBackground': '#1f2428',
    'tab.inactiveForeground': '#959da5',
    'tab.unfocusedActiveBorder': '#24292e',
    'tab.unfocusedActiveBorderTop': '#1b1f23',
    'tab.unfocusedHoverBackground': '#24292e',
    'terminal.foreground': '#d1d5da',
    'textBlockQuote.background': '#24292e',
    'textBlockQuote.border': '#444d56',
    'textCodeBlock.background': '#2f363d',
    'textLink.activeForeground': '#c8e1ff',
    'textLink.foreground': '#79b8ff',
    'textPreformat.foreground': '#d1d5da',
    'textSeparator.foreground': '#586069',
    'titleBar.activeBackground': '#24292e',
    'titleBar.activeForeground': '#e1e4e8',
    'titleBar.border': '#1b1f23',
    'titleBar.inactiveBackground': '#1f2428',
    'titleBar.inactiveForeground': '#959da5',
    'tree.indentGuidesStroke': '#2f363d',
  },
  rules: [
    {
      foreground: '#5F6167',
      token: 'comment',
    },
    {
      foreground: '#5F6167',
      token: 'markup.quote.markdown',
    },
    {
      foreground: '#5F6167',
      token: 'meta.diff',
    },
    {
      foreground: '#5F6167',
      token: 'meta.diff.header',
    },
    {
      foreground: '#D5CED9',
      token: 'meta.template.expression.js',
    },
    {
      foreground: '#D5CED9',
      token: 'constant.name.attribute.tag.jade',
    },
    {
      foreground: '#D5CED9',
      token: 'punctuation.definition.metadata.markdown',
    },
    {
      foreground: '#D5CED9',
      token: 'punctuation.definition.string.end.markdown',
    },
    {
      foreground: '#D5CED9',
      token: 'punctuation.definition.string.begin.markdown',
    },
    {
      foreground: '#00E8C6',
      token: 'variable',
    },
    {
      foreground: '#00E8C6',
      token: 'support.variable',
    },
    {
      foreground: '#00E8C6',
      token: 'entity.name.tag.yaml',
    },
    {
      foreground: '#00E8C6',
      token: 'constant.character.entity.html',
    },
    {
      foreground: '#00E8C6',
      token: 'source.css entity.name.tag.reference',
    },
    {
      foreground: '#00E8C6',
      token: 'beginning.punctuation.definition.list.markdown',
    },
    {
      foreground: '#00E8C6',
      token: 'source.css entity.other.attribute-name.parent-selector',
    },
    {
      foreground: '#00E8C6',
      token: 'meta.structure.dictionary.json support.type.property-name',
    },
    {
      foreground: '#F39C12',
      token: 'markup.bold',
    },
    {
      foreground: '#F39C12',
      token: 'constant.numeric',
    },
    {
      foreground: '#F39C12',
      token: 'meta.group.regexp',
    },
    {
      foreground: '#F39C12',
      token: 'constant.other.php',
    },
    {
      foreground: '#F39C12',
      token: 'support.constant.ext.php',
    },
    {
      foreground: '#F39C12',
      token: 'constant.other.class.php',
    },
    {
      foreground: '#F39C12',
      token: 'support.constant.core.php',
    },
    {
      foreground: '#F39C12',
      token: 'fenced_code.block.language',
    },
    {
      foreground: '#F39C12',
      token: 'constant.other.caps.python',
    },
    {
      foreground: '#F39C12',
      token: 'entity.other.attribute-name',
    },
    {
      foreground: '#F39C12',
      token: 'support.type.exception.python',
    },
    {
      foreground: '#F39C12',
      token: 'source.css keyword.other.unit',
    },
    {
      foreground: '#F39C12',
      token: 'variable.other.object.property.js.jsx',
    },
    {
      foreground: '#F39C12',
      token: 'variable.other.object.js',
    },
    {
      foreground: '#FFE66D',
      token: 'markup.list',
    },
    {
      foreground: '#FFE66D',
      token: 'text.xml string',
    },
    {
      foreground: '#FFE66D',
      token: 'entity.name.type',
    },
    {
      foreground: '#FFE66D',
      token: 'support.function',
    },
    {
      foreground: '#FFE66D',
      token: 'entity.other.attribute-name',
    },
    {
      foreground: '#FFE66D',
      token: 'meta.at-rule.extend',
    },
    {
      foreground: '#FFE66D',
      token: 'entity.name.function',
    },
    {
      foreground: '#FFE66D',
      token: 'entity.other.inherited-class',
    },
    {
      foreground: '#FFE66D',
      token: 'entity.other.keyframe-offset.css',
    },
    {
      foreground: '#FFE66D',
      token: 'text.html.markdown string.quoted',
    },
    {
      foreground: '#FFE66D',
      token: 'meta.function-call.generic.python',
    },
    {
      foreground: '#FFE66D',
      token: 'meta.at-rule.extend support.constant',
    },
    {
      foreground: '#FFE66D',
      token: 'entity.other.attribute-name.class.jade',
    },
    {
      foreground: '#FFE66D',
      token: 'source.css entity.other.attribute-name',
    },
    {
      foreground: '#FFE66D',
      token: 'text.xml punctuation.definition.string',
    },
    {
      foreground: '#FF00AA',
      token: 'markup.heading',
    },
    {
      foreground: '#FF00AA',
      token: 'variable.language.this.js',
    },
    {
      foreground: '#FF00AA',
      token: 'variable.language.special.self.python',
    },
    {
      foreground: '#00E8C6',
      token: 'punctuation.definition.interpolation',
    },
    {
      foreground: '#00E8C6',
      token: 'punctuation.section.embedded.end.php',
    },
    {
      foreground: '#00E8C6',
      token: 'punctuation.section.embedded.end.ruby',
    },
    {
      foreground: '#00E8C6',
      token: 'punctuation.section.embedded.begin.php',
    },
    {
      foreground: '#00E8C6',
      token: 'punctuation.section.embedded.begin.ruby',
    },
    {
      foreground: '#00E8C6',
      token: 'punctuation.definition.template-expression',
    },
    {
      foreground: '#00E8C6',
      token: 'entity.name.tag',
    },
    {
      foreground: '#C74DED',
      token: 'storage',
    },
    {
      foreground: '#C74DED',
      token: 'keyword',
    },
    {
      foreground: '#C74DED',
      token: 'meta.link',
    },
    {
      foreground: '#C74DED',
      token: 'meta.image',
    },
    {
      foreground: '#C74DED',
      token: 'markup.italic',
    },
    {
      foreground: '#C74DED',
      token: 'source.js support.type',
    },
    {
      foreground: '#7CB7FF',
      token: 'string.regexp',
    },
    {
      foreground: '#7CB7FF',
      token: 'markup.changed',
    },
    {
      foreground: '#00E8C6',
      token: 'constant',
    },
    {
      foreground: '#00E8C6',
      token: 'support.class',
    },
    {
      foreground: '#00E8C6',
      token: 'keyword.operator',
    },
    {
      foreground: '#00E8C6',
      token: 'support.constant',
    },
    {
      foreground: '#00E8C6',
      token: 'text.html.markdown string',
    },
    {
      foreground: '#00E8C6',
      token: 'source.css support.function',
    },
    {
      foreground: '#00E8C6',
      token: 'source.php support.function',
    },
    {
      foreground: '#00E8C6',
      token: 'support.function.magic.python',
    },
    {
      foreground: '#00E8C6',
      token: 'entity.other.attribute-name.id',
    },
    {
      foreground: '#00E8C6',
      token: 'markup.deleted',
    },
    {
      foreground: '#96E072',
      token: 'string',
    },
    {
      foreground: '#96E072',
      token: 'text.html.php string',
    },
    {
      foreground: '#96E072',
      token: 'markup.inline.raw',
    },
    {
      foreground: '#96E072',
      token: 'markup.inserted',
    },
    {
      foreground: '#96E072',
      token: 'punctuation.definition.string',
    },
    {
      foreground: '#96E072',
      token: 'punctuation.definition.markdown',
    },
    {
      foreground: '#96E072',
      token: 'text.html meta.embedded source.js string',
    },
    {
      foreground: '#96E072',
      token: 'text.html.php punctuation.definition.string',
    },
    {
      foreground: '#96E072',
      token: 'text.html meta.embedded source.js punctuation.definition.string',
    },
    {
      foreground: '#96E072',
      token: 'text.html punctuation.definition.string',
    },
    {
      foreground: '#96E072',
      token: 'text.html string',
    },
    {
      fontStyle: 'underline',
      token: 'entity.other.inherited-class',
    },
    {
      foreground: '#6796E6',
      token: 'token.info-token',
    },
    {
      foreground: '#CD9731',
      token: 'token.warn-token',
    },
    {
      foreground: '#F44747',
      token: 'token.error-token',
    },
    {
      foreground: '#B267E6',
      token: 'token.debug-token',
    },
  ],
  encodedTokensColors: [],
};

export const options = {
  minimap: {
    enabled: false,
  },
  fontFamily: 'Roboto Mono, monospace',
  selectOnLineNumbers: true,
  tabSize: 2,
  fontSize: 15,
  lineHeight: 23,
  wordWrap: 'on' as const,
};
